
# SEO settings
title: "ops"
title2: "plus" # default: ""
description: "We do all the IT Operations. DevOps, WebOps, SecOps, SysOps, CloudOps etc."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://opsplus.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/opsplus/opsplus.github.io
disqus_shortname: "opsplus"
twitter_username: "opsplus_io"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "akprajapati"
  job      : "OpsPlus Engineer"
  bio      : "DevOps, WebOps, SecOps, SysOps, CloudOps and more."
  thumb    : /images/author.jpg
  email    : akplive139@gmail.com
  url      : http://opsplus.github.io
  github   : http://github.com/opsplus
  twitter  : http://twitter.com/opsplus_io
  facebook : https://www.facebook.com/opsplus
  linkedin : http://linkedin.com/in/opsplus

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@opsplus_io"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
