# Site
repository:
favicon: images/akjprajapati.ico

# Content configuration version
version: 2

# Personal info
name: ASHISH KUMAR
title: A DevOps Engineer.
email: ak@prajapati.live
website:

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: akjprajapati
github_username:  akjprajapati
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: akjprajapati
# flickr_username: jekyll
instagram_username: akjprajapati
linkedin_username: akjprajapati
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: prajapati.akj
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: ak.prajapati.io
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/akjprajapati.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm a DevOps Engineer. I've total 11 years of IT Experience. I have worked at a number of companies gaining teamwork and leadership skills.

  I'm skilled in: <mark>AWS</mark> <mark>Linux</mark> <mark>Bash</mark> <mark>Terraform</mark> <mark>Ansible</mark> <mark>Jenkins</mark> <mark>Docker</mark> <mark>Kubernetes</mark>

content:
  # - title: PROJECTS # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: My project
  #       link: github.com/akjprajapati
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kloud9 Technologies Pvt. Ltd.
        link: https://kloud9.nyc/
        link_text: Koud9 Technologies
        sub_title: Lead DevOps and SRE.
        caption: Feb 2022 - Nov 2022
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Roles and responsibilities—
                ➢ Automating the infra provisioning using terraform for AWS, GCP and Azure cloud platforms.
                ➢ Automating tasks using ansible playbooks and bash / python scripts.
                ➢ Working on serverless projects which involve lambda and serverless framework.
            Projects—
                ➢ Modularization of the terraform code.
                ➢ Implementation of terraform for Kubernetes resource creation on cloud platforms.
                ➢ Implementation of packer and ansible provisioner with terraform.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IIMT ENGINEERING COLLEGE
        caption: 2007 - 2011
        sub_title: B.Tech, Electronics and communications.
        quote: >
          Completed my engineering.
        description: | # this will include new lines to allow paragraphs
          Completed my engineering in Electronics and communications.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
